cookie:
  expiry_days: 30
  key: romanjewish_auth_cookie_secret_key_2026
  name: romanjewish_auth_cookie
credentials:
  usernames:
    yair:
      email: yair@example.com
      failed_login_attempts: 0
      first_name: Yair
      last_name: Furstenberg
      logged_in: false
      password: riay
    david:
      email: david@example.com
      failed_login_attempts: 0
      first_name: David
      last_name: Flam
      logged_in: false
      password: divad
    esther:
      email: esther@example.com
      failed_login_attempts: 0
      first_name: Esther
      last_name: Shizgal
      logged_in: false
      password: rehtse
