cookie:
  expiry_days: 30
  key: romanjewish_auth_cookie_secret_key_2026
  name: romanjewish_auth_cookie
credentials:
  usernames:
    yair:
      email: yair@example.com
      failed_login_attempts: 0
      first_name: Yair
      last_name: Furstenberg
      logged_in: false
      password: yair
    david:
      email: david@example.com
      failed_login_attempts: 0
      first_name: David
      last_name: Flam
      logged_in: false
      password: david
    esther:
      email: esther@example.com
      failed_login_attempts: 0
      first_name: Esther
      last_name: Shizgal
      logged_in: false
      password: rehtse
    gil:
      email: gil@example.com
      failed_login_attempts: 0
      first_name: Gil
      last_name:
      logged_in: false
      password: lig
    antonio:
      email: antonio@example.com
      failed_login_attempts: 0
      first_name: Antonio
      last_name:
      logged_in: false
      password: antonio
    jan:
      email: jan@example.com
      failed_login_attempts: 0
      first_name: Jan
      last_name:
      logged_in: false
      password: jan
    sonya:
      email: sonya@example.com
      failed_login_attempts: 0
      first_name: Sonya
      last_name:
      logged_in: false
      password: sonya
    noemie:
      email: noemie@example.com
      failed_login_attempts: 0
      first_name: Noemie
      last_name:
      logged_in: false
      password: noemie
    daniel:
      email: daniel@example.com
      failed_login_attempts: 0
      first_name: Daniel
      last_name:
      logged_in: false
      password: daniel
    hillel:
      email: hillel@example.com
      failed_login_attempts: 0
      first_name: Hillel
      last_name:
      logged_in: false
      password: hillel
    shlomi:
      email: hillel@example.com
      failed_login_attempts: 0
      first_name: Shlomi
      last_name:
      logged_in: false
      password: shlomi
    matti:
      email: matti@example.com
      failed_login_attempts: 0
      first_name: Matti
      last_name:
      logged_in: false
      password: matti

