# .streamlit/secrets.toml

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1cb4Pmc7SFCZ3C5kJD8kkDFQsuJXdk16a1afoRElJ3L0/edit?gid=0#gid=0"
type = "service_account"
project_id = "romanjewishlaw"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCjN3DJciQ44G6s\nZF15ZdAegN9fL4BkXuA9HJBOaoW7q/w78JSfsaleoCiPwjwG9Fwd1lm1kYVNsFFC\nc1MscNxwxf8GeqaTSXQ4Qqn8n8jq5IMHRgCThMhgKdmnfqLVxbXyFdk7EhUmrTIW\nhA6XvPXshOFAgFW9uKzgC4nyEHsctY/K8i83LEed+b103Y0Z6PC+fzs/XqDxbgFc\nt6yw1x0XIMKkBZWhJ3WiYNRO2P5Ep/+dj9P+b+CREX85c8YqDuPmKer83ccNEzbt\no9rkWGlfShxV+Nhs78WFpREz2r/cHddy4AgmXco8q/vUl5sD7dJ+mjzsZSPSJZN6\nTqFBebuLAgMBAAECggEAJabf+3C7320Syu0aTSuKD8deADjWjxD9/MsOlTBoqmsZ\n9H/i4VYcQsqCoOtHarlLWMy+hC7OSCZBEKnHCaz9hXx/gPChZb/fsizaxv7bXCib\n+30QG/fZO6nb3pJNoTALcY3Nv51DyNjSgbQ0I5gBSW88AWO5o9sq8kJnL7LSm8P+\nRx0Tpi2xHkdC2DmItnYTyH11Gj+bQHy+Z69OZsr4D7EEnfrIlAm3B0WE8Rmf3IaV\nvg2zGGIye8dbtxVJT/nDkFwbmbOvhAgQtwxb6jN81o83B2PqoIsnzUPnjUt/PSFT\nFzgqNLoeaW2ETQrlZbuwkqwjOtlQhNJr8xVUA0454QKBgQDUZ/ERkL+slEPk3idQ\ng+oM6k1xHMq34b3z9PcQimnsbsgjH84QSjcB4x5yc7B/bSEhP4oa5fFWGOkNdhgQ\nvOr8pLEGCKOXvd7hwVLgWqz3MM4keEPueapex8t9fg1JQDcICeh82P8hKVIFedvM\nyHzVaCG0kBqypAoBnFtRFGHB4QKBgQDEtwchilOojzHEcoC/J9NImpfZ3ubj2lLh\nhDRcnb8SUdFXSgusEXM9nw+DIJCkVCu5ByQBR3pnLn59L3MJGIZ4FKo2S14asJ41\nvmUpzhA2iN8EBab+psNz0tfchKvEKwAc1+pazL3yrp5rC+YwjQXIAWcaFdLjvus4\nxkPcgVkC6wKBgGxRWVlY1LZgocL8G1Zu/xN5BOcTBLoDL8hR+xB/VYcR85Qd6wrZ\nnfWjaep53t8MuuFmsroG2yzJ5UdNGvamMLuIDRKDo1GFrTy5RtdMxnoEdIuanSHm\n/5/4CWjEuGfLjITX8KyCSJETrlVGkHV9JFP8F3wqJMNG7idmIhdV6ohhAoGAYg/T\ncDbiqV5ossNZxvD1dHYMSMHDW8aUFnOvHpRMkbdToi35T5eLWSaXtwhe0mxbN2uF\n2VVmgVU+HO2wbNJbBjVW/KXpjWiKFcSJ7aMZlfX5Jqoiq0M6n9x1WyqP7cR50+cW\nnpj9/6Joung+Eena/e8lFG3YqUudOrorThr04m0CgYB13+WcDysRE5CZ7GjyIBke\nvirkDP6tfyK4K7ux7bBxXoHCxmnQ63rinvbOTDjDDMVZQAkTwhTKbaBdY9WPv3oc\nqCUpr2L0ED9uHIm8n9NEMe9iF1OhlUaUeWBvpnzgpR07lzk8MCAwu2MWMybkISTI\nYJRhVEYusGnKDbmOY6a0eQ==\n-----END PRIVATE KEY-----\n"
private_key_id = "6983c0ad07a9e31c996b4f4dfe0e68d555c03b5c"
client_email = "streamlit-bot@romanjewishlaw.iam.gserviceaccount.com"
client_id = "101440115637294264451"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-bot%40romanjewishlaw.iam.gserviceaccount.com"

# --- Authentication Config ---
[auth_cookie]
expiry_days = 30
key = "romanjewish_auth_cookie_secret_key_2026"
name = "romanjewish_auth_cookie"

[auth_credentials.usernames.yair]
email = "yair@example.com"
failed_login_attempts = 0
first_name = "Yair"
last_name = "Furstenberg"
logged_in = false
password = "riay"

[auth_credentials.usernames.david]
email = "david@example.com"
failed_login_attempts = 0
first_name = "David"
last_name = "Flam"
logged_in = false
password = "divad"

[auth_credentials.usernames.esther]
email = "esther@example.com"
failed_login_attempts = 0
first_name = "Esther"
last_name = "Shizgal"
logged_in = false
password = "rehtse"
